variables = {
    'FILE_PATH': './test/samples/'
}

VOLUME_FILE = 'volumes.json'

CURRENT_EBS_TYPE = 'gp2'
DESIRED_EBS_TYPE = 'gp3'

DEVEL_VPC = 'YOUR DEVEL VPC ID'
PRODUCT_VPC = 'YOUR PRODUCT VPC ID'
MANAGE_VPC = 'YOUR MANAGE VPC ID'
